### ISSUE TITLE
possibility of opening up more options/settings?

### ISSUE THREAD

**Issue by hqhoang** [PetteriAimonen/focus-stack#19]
hi, your project was mentioned and I'm very impressed after trying it out.
https://discuss.pixls.us/t/macrofusion-rewritten-in-tkinter/30118

I'm working on a GUI for enfuse, would love to utilize your tool as one of the options available. If you're OK with it, I wonder if you could expose a few more settings, e.g. ECC settings, a stack-only mode. Currently you already have align-only mode that I could make use of as an aligner.

https://github.com/hqhoang/mftker

thanks.

P.S. I see faint ghosting outlines in my test shots output from your focus-stack tool, wondering if maybe dialing back a little bit on whatever halo-reducing technique would help? Does one of the current settings do that already?

**Comment by PetteriAimonen** [comment]
The ghost lines are probably due to lack of halo filtering, issue #8.

About exposing more settings, in principle I have nothing against it but I'm probably not going to work on doing that myself.
And I think there should be a strong usecase for exposing new settings, instead of just "bring all out just in case".

**Comment by hqhoang** [comment]
Thanks! Sounds good.
