### ISSUE TITLE
Problems near borders

### ISSUE THREAD

**Issue by raduprv** [PetteriAimonen/focus-stack#2]
Hi, it's me again.
I compiled the new version, and I found some other problems (they are present in the old and new version also).

Here are the files
![output](https://user-images.githubusercontent.com/1095519/77327524-09ddc300-6d24-11ea-8848-9fa914b7eaeb.jpg)
![img_test000000](https://user-images.githubusercontent.com/1095519/77327533-0e09e080-6d24-11ea-8e25-3743e55eb46a.jpg)
![img_test000001](https://user-images.githubusercontent.com/1095519/77327538-0f3b0d80-6d24-11ea-90d8-99c38ef82f56.jpg)
![img_test000002](https://user-images.githubusercontent.com/1095519/77327540-0f3b0d80-6d24-11ea-8949-42359a993ebb.jpg)
![img_test000003](https://user-images.githubusercontent.com/1095519/77327541-0fd3a400-6d24-11ea-8122-ae3bced418b7.jpg)
![img_test000004](https://user-images.githubusercontent.com/1095519/77327542-0fd3a400-6d24-11ea-8300-f03a2299e331.jpg)

**Comment by PetteriAimonen** [comment]
This seems to be caused by the large distance difference between the background and foreground, which causes a lot of scale change between the images. When they get aligned, some images are too small and the border is artificially expanded.

The problem near top edge could probably be handled by keeping track of the original area of the image and changing Task_Reassign to only take into account pixels that are actually from input image. Not sure what could be done about the artifacts around the chair.

**Comment by raduprv** [comment]
Could you make an option to make the resulting image in such a way that all the images are downscaled to match the smallest image? That should take care of artifacts resulting from upsampling many images.

**Comment by PetteriAimonen** [comment]
Yeah, that is one option also. In any case, it would need tracking of the source image areas through the transformation done by `Task_Align`; not particularly difficult to do, just needs to be added.
