### ISSUE TITLE
“focus-stack.app” is damaged and can’t be opened. You should move it to the Trash.

### ISSUE THREAD

**Issue by groeneveld** [PetteriAimonen/focus-stack#23]
MacOS 12.4
M1 MacbookAir

I downloaded the binaries for 1.4 and 1.3 and opening either brings up a dialog with "“focus-stack.app” is damaged and can’t be opened. You should move it to the Trash."

**Comment by PetteriAimonen** [comment]
I don't have M1 hardware to test, just an on Mac OS X Catalina virtual machine.

But a common cause for that error message is because Mac OS X doesn't like unsigned applications. Apple signing certificates are quite expensive so currently I have no plans of buying one for a free application.

You can try `xattr -d com.apple.quarantine focus-stack.app` from command line, on Mac OS X Catalina it allows running the program.

**Comment by groeneveld** [comment]
That did it. Thanks!

**Comment by PetteriAimonen** [comment]
Thanks for confirming, I added it to readme now :)
